import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lemonMilk = localFont({
  src: [
    {
      path: "./fonts/LEMONMILK-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/LEMONMILK-LightItalic.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/LEMONMILK-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/LEMONMILK-RegularItalic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/LEMONMILK-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/LEMONMILK-MediumItalic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/LEMONMILK-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/LEMONMILK-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-lemon-milk",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lemonMilk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
